[package]
name = "steamkit-lang"
version = "0.1.0"
edition = "2021"
build = "build/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.3"
num-traits = "0.2"

[build-dependencies]
syn = "2.0"